### ISSUE TITLE
[BUG] Local dev and serve require env vars

### ISSUE THREAD

**Issue by cjerrington** [ttntm/bukmark.club#13]
**Describe the bug**
While testing the serve of the site locally, I got an error for the netlify api and caused the local build as `dev` to fail. 

**To Reproduce**
1. Clone site new
2. run `npm i` to install dependencies
3. run `npm run serve`
    -  While on Windows and a `pwsh` terminal, `rm` was not a recognized command. 
    - Thoughts on making this more cross environment? 
4. Alternative `npx @11ty\eleventy --serve`

**Expected behavior**
Start an 11ty/BrowserSync session to view the built site locally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Would be Firefox 
 - Version:131.0.2

**Additional context**
I use [rimraf](https://www.npmjs.com/package/rimraf) to do some similar clean up on my site for this cross environmental clean up.

**Comment by ttntm** [comment]
Valid input, thanks for letting me know.

I'll make sure the site builds without the private env variables needed for the guestbuk data, and I'll also look into cross platform support.

**Comment by ttntm** [comment]
fixed with https://github.com/ttntm/bukmark.club/commit/b85a22e7ff1bf81445f84ff09f3fd9f439292274
