### ISSUE TITLE
[FEAT] Have updating the `info.json` be run on build

### ISSUE THREAD

**Issue by cjerrington** [ttntm/bukmark.club#14]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
While manually forking the repository and committing the changes, I saw we needed to have the `info.json` as part of the commit. While this is done on the `serve` and not `deploy` that builds the site, should it be a requirement for adding a user's `site.md` file? 

**Describe alternatives you've considered**
When you can properly `serve` the local version (#13), it calls the `info` script command, which runs the required steps. To properly generate this file, I had to delete the file and call the `node` script directly to ensure the date time was in a correct timestamp. 

**Additional context**
This might make contributing slightly easier for others if these processes were handled in the `build` and `deployed` stage as well.

**Comment by ttntm** [comment]
It used to be like that - stats were re-generated with every build.

But: there was some issue with the data, it ended up being wrong for some reason. I think it was related to builds having a completely fresh filesystem every time, and that made a mess somehow.

I'll check - it would indeed make the process of contributing to this project a little easier.

**Comment by ttntm** [comment]
Ok, got it: `info.json` includes a `mostRecentUpdate` which I added as an alternative to adding a date to individual listings. 

It's a hacky workaround for proper data maintenance, and it's wrong as soon as there's a) more than 1 contributor, or b) the script runs in a build context (new repo clone, all files created at build time).

I like the distinction between the last build date (in the footer) and the "Last site added" date on both the homepage and the directory page. But that's a personal preference and probably doesn't add much to the project as a whole anyway. 

I'll remove it and tune the scripts in favor of easier maintenance and contributions.

**Comment by ttntm** [comment]
improved with https://github.com/ttntm/bukmark.club/commit/b85a22e7ff1bf81445f84ff09f3fd9f439292274
